Document: python-whisper
Title: Debian python-whisper Manual
Author: <insert document author here>
Abstract: This manual describes what python-whisper is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-whisper/python-whisper.sgml.gz

Format: postscript
Files: /usr/share/doc/python-whisper/python-whisper.ps.gz

Format: text
Files: /usr/share/doc/python-whisper/python-whisper.text.gz

Format: HTML
Index: /usr/share/doc/python-whisper/html/index.html
Files: /usr/share/doc/python-whisper/html/*.html
